# Generated by Django 3.0.6 on 2020-05-31 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('family', models.CharField(help_text='Enter the family of the component', max_length=100)),
                ('ref', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Enter the description of the product', max_length=100)),
                ('location', models.CharField(help_text='Location of equipment', max_length=10)),
                ('total_items', models.IntegerField()),
                ('borrowed_items', models.IntegerField()),
                ('price', models.FloatField()),
                ('broken', models.CharField(blank=True, choices=[('yes', 'broken'), ('no', 'ok')], default='no', help_text='Condition of the equipment', max_length=3)),
                ('status', models.CharField(blank=True, choices=[('dis', 'Available'), ('ind', 'Unavailable')], default='dis', help_text='Status of equipment', max_length=3)),
                ('image_file', models.ImageField(blank=True, upload_to='equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('cod_group', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('teacher', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('equipment', models.ManyToManyField(to='technician_api.Equipments')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nmec', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('mail', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending request'), ('denied', 'denied'), ('approved', 'approved')], default='pending', help_text='Status of the request', max_length=32)),
                ('equipment_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Equipments')),
                ('project_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=64, null=True)),
                ('equipment_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Equipments')),
                ('group_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Group')),
                ('project_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Project')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='cod_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technician_api.Project'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='technician_api.Student'),
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('year', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('component_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Equipments')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('supplier', models.CharField(max_length=64)),
                ('price_iva', models.IntegerField()),
                ('price_unity', models.CharField(max_length=16)),
                ('component_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Equipments')),
            ],
        ),
    ]
