# Generated by Django 3.0.6 on 2020-06-25 14:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technician_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipments',
            options={'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='missing',
            options={'verbose_name_plural': 'Missing'},
        ),
        migrations.AddField(
            model_name='request',
            name='dateAcknowledged',
            field=models.DateTimeField(null=True, verbose_name='Date approved/denied'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of the exit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='technician_api.Equipments'),
        ),
        migrations.AlterField(
            model_name='request',
            name='equipment_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Equipments', verbose_name='Requested equipment'),
        ),
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date requested'),
        ),
    ]
